the1812/Bilibili-Evolved

- src/style/dark/dark-slice-13.scss
- src/utils/remove-promotions/remove-promotions.css
- 修复：#1060 （貌似这个排行榜页面底部的这个广告并不总会出现。。。）
- 部分修复：#731（之前提的互动视频对话框）
> fix #1060, etc

- CONTRIBUTING.md
- bilibili-evolved.greasy.user.js
- bilibili-evolved.offline.user.js
- bilibili-evolved.preview-offline.user.js
- bilibili-evolved.preview.user.js
- bilibili-evolved.user.js
- src/client/bilibili-evolved.js
> Add exclude rule

- CONTRIBUTING.md
- bilibili-evolved.greasy.user.js
- bilibili-evolved.offline.user.js
- bilibili-evolved.preview-offline.user.js
- bilibili-evolved.preview.user.js
- bilibili-evolved.user.js
- src/client/bilibili-evolved.js
> Update exclude rule

- src/video/keymap/keymap.ts
> 拜年纪活动页快捷键扩展支持

- src/style/dark/_dark-definitions.scss
- src/style/dark/dark-slice-14.scss
- src/style/dark/dark-slice-bnj2021.scss
米娜桑，新年快乐🎉🎉🎉
- 2021 拜年纪收藏/投币对话框（投币对话框因图片大小尺寸不合，强行更改背景色非常违和，故只修了主题色
- b 币账户/贝壳账户 .balance-name
- 收藏对话框的新建按钮背景色（原来是透明的）
- 播放器缓冲图标主题色适配
> dark style

- src/video/video-speed/video-speed-controller.ts
> 修复记忆倍数功能失效

- src/style/simplify-home/simple-home/blackboard.ts
fix #1483 
自己用的时候也遇到了, 跑来看下了果然有issue...
B站自己这个轮播图都有bug...如果没有5个item然后点最后一页后就会出现奇怪的化学反应(
它虽然有5格位置, 但有时候居然不一样有5个元素
> 改进getBlackboards

- src/style/dark/dark-slice-10.scss
> fix(dark style): 过期后的预约按钮

- src/utils/url-params-clean.ts
> Fix https://github.com/the1812/Bilibili-Evolved/issues/2165

- registry/lib/components/style/dark-mode/dark-slice-10.scss
- registry/lib/components/style/dark-mode/dark-slice-15.scss
> V2 dark mode

- registry/lib/components/style/dark-mode/follow-system/index.ts
https://github.com/the1812/Bilibili-Evolved/pull/1812
这个更改好像没有迁移过来
> 更新`夜间模式跟随系统`的说明

- registry/lib/components/live/gift-box/index.ts
> 添加`直播全屏包裹`说明中缺失的句号

- registry/lib/components/video/player/remember-speed/controller.ts
- registry/lib/components/video/player/remember-speed/extend.ts
- registry/lib/components/video/player/remember-speed/index.ts
- registry/lib/components/video/player/remember-speed/utils.ts
- src/core/settings/index.ts
fix: #2561
以前的代码现在看来很多设计都不必要，于是重构了一波
> fix: #2561

- registry/lib/components/video/player/auto-light/index.ts
> Fix context loss in auto-light

- .vscode/settings.json
- registry/lib/components/video/player/default-mode/index.ts
> Fix default-mode

- src/components/settings-panel/sub-pages/online-registry/OnlineRegistry.vue
- src/components/settings-panel/sub-pages/online-registry/RegistryItem.vue
> fix: 修复在现安装时分支选择无效（Issue #2849）

- src/ui/VSlider.vue
该参数会导致组件的可取值、可取值的大小顺序、最大最小值等关键数据无法预测。组件难以对这些意料之外的情况作出应对，也因此可能会产生一些不易追查的 bug。保险起见，还是决定暂时删除这个属性。
修正后：若 min 与 max 范围内没有可取值，会将值固定为大于 min 的最小对齐值，并且会发出一个控制台 error 日志。
修改组件描述，使其更易理解。
> 去除 VSlider 中的 fix-num 参数，修正边缘行为，修改该组件的描述

- registry/lib/components/video/player/default-mode/index.ts
> Fix default mode (fix #2894)

- .vscode/settings.json
- src/core/utils/urls.ts
> 修复 urls.ts 的 Bug（#2986, #2987）

- registry/lib/components/video/player/screenshot/index.ts
留给别人的TODO: 支持WASM播放器的视频截图功能
另见 #3046
> fix: 修复了启用视频截图后WASM播放器上截图失败后不提示反而无限加载截图的问题

- src/components/auto-update/index.ts
- src/components/i18n/index.ts
- src/components/launch-bar/index.ts
- src/components/notify-new-version/index.ts
- src/components/settings-panel/index.ts
- src/core/settings/helpers.ts
> Change buildin components to define api

- .github/workflows/build.yml
GitHub action 用 bot 去构建提高提交历史区分度
> Update github action

- registry/lib/components/video/player/common/speed/context.ts
- registry/lib/components/video/player/common/speed/utils.ts
- registry/lib/components/video/player/extend-speed/component.ts
- registry/lib/components/video/player/skip-charge-list/charge-list.scss
- registry/lib/components/video/player/skip-charge-list/index.ts
- src/components/video/player-agent.ts
- src/core/observer.ts
> 适配3.X的aid获取方式，同时支持2.X

- src/components/video/player-agent.ts
> Improve lightoff behaviour in player-agent

- src/components/video/player-agent.ts
#3398 
另外提一嘴，建议提醒用户使用高版本浏览器内核(
> 使bwp-video模式下正确更新相关selector

- src/components/feeds/VideoCard.vue
> 修复在 Safari 浏览器下 transform 的时候圆角变方框

- registry/lib/components/utils/black-list/BlockListSettings.vue
- registry/lib/components/utils/black-list/NavbarSettings.vue
- registry/lib/components/utils/black-list/Settings.vue
- registry/lib/components/utils/black-list/common.ts
- registry/lib/components/utils/black-list/index.ts
- registry/lib/components/utils/black-list/vm.ts
> up主黑名单，删除首页的黑名单up主封面、名称、标题

- registry/lib/components/video/player/default-mode/index.ts
- registry/lib/components/video/player/intersection-actions/index.ts
> fix(default-mode,intersection): fix entry blocking ComponentsLoaded

- registry/lib/components/feeds/copy-link/index.ts
- registry/lib/components/feeds/disable-details/index.ts
- registry/lib/components/feeds/extend-live/index.ts
- registry/lib/components/feeds/filter/index.ts
- registry/lib/components/feeds/fixed-sidebars/index.ts
- registry/lib/components/feeds/fold-comments/index.ts
- registry/lib/components/feeds/full-content/index.ts
- registry/lib/components/feeds/full-title/index.ts
- registry/lib/components/feeds/unfold/index.ts
> Change feeds to define api

- registry/lib/components/style/dark-mode/follow-system/index.ts
- registry/lib/components/style/dark-mode/schedule/index.ts
- registry/lib/components/style/simplify/home/index.ts
- registry/lib/components/style/simplify/live/index.ts
- registry/lib/components/touch/mini-player/touch-move.ts
- registry/lib/components/touch/player-gestures/swiper.ts
- registry/lib/components/utils/image-exporter/feed.ts
- registry/lib/components/utils/image-exporter/index.ts
- registry/lib/components/utils/image-resolution/index.ts
- registry/lib/components/utils/image-resolution/resolution.ts
- registry/lib/components/utils/keymap/actions.ts
- registry/lib/components/utils/keymap/index.ts
- registry/lib/components/video/player/common/speed.ts
- registry/lib/components/video/player/extend-speed/component.ts
- registry/lib/components/video/player/remember-speed/component.ts
- registry/lib/docs/index.ts
- registry/lib/plugins/style/custom-navbar-channel/index.ts
- src/components/auto-update/checker.ts
- src/components/auto-update/index.ts
- src/components/i18n/helpers.ts
- src/components/i18n/machine-translator/translators.ts
- src/components/i18n/types.ts
- src/components/styled-component.ts
- src/components/switch-options.ts
- src/components/types.ts
- src/core/settings/helpers.ts
我目前能想到的都搞定了。但项目挺大，有所遗漏也说不定。
改动大的地方我简单试了一下，目前没发现什么问题。
> define API 收尾工作完成

- registry/lib/components/video/player/common/speed.ts
- registry/lib/components/video/player/extend-speed/component.ts
> fix(extend-speed): 修复3.x播放器1.5x倍速可能无法点击的问题

- registry/lib/components/feeds/fold-comments/index.ts
> 快速收起评论: 收起评论时使用平滑滚动

- registry/lib/components/video/player/show-upload-time/index.ts
> 显示视频投稿时间适配新版页面

- registry/lib/components/utils/import-series/logic.ts
应该弄好了？但是不知道怎么测试
本地服务器一直都是正常状态，不知道怎么在生产环境下测试
> fix bug #3902

- src/components/settings-panel/WidgetsPanel.vue
> Update default empty content (fix #3932)

- registry/lib/components/video/player/show-cover/index.ts
> 使得--cover-url正确的被移除

- registry/lib/components/style/dark-mode/old/dark-slice-1.css
fix #1052
样例页面：https://www.bilibili.com/v/car/modifiedvehicle
> [组件:夜间模式] 修复鼠标移至特定页排行榜时的显示问题

- registry/lib/components/utils/import-series/logic.ts
- registry/lib/components/video/player/extend-speed/component.ts
- src/components/i18n/dom-translator.ts
- src/core/utils/index.ts
> Fix lint errors/warnings

- registry/lib/components/style/custom-navbar/iframe/IframePopup.vue
- registry/lib/components/style/custom-navbar/iframe/iframe.ts
Fix type errors of IframePopup.vue (#3947)
> Fix type errors of IframePopup.vue (#3947)

- .github/ISSUE_TEMPLATE/bug_report.yml
> 📝feat(docs): add kind reminder in Issue template

- src/components/switch-options.ts
不再要求必须使用 `defineSwitchMetadata` 定义 `SwitchMetadata`
> 修改了一些 switch-options.ts 里的注释

- registry/lib/components/feeds/extend-live/index.ts
https://github.com/the1812/Bilibili-Evolved/issues/4034
> fix extend-live

- registry/lib/components/live/gift-box/gift-box.scss
https://github.com/the1812/Bilibili-Evolved/issues/4105#issuecomment-1492975102
> 修改一个由于疏忽产生的css错误，修复#4105 道具包裹css样式错误

- registry/lib/components/video/player/show-upload-time/index.ts
1. 新增了一个设置项`文本格式`
2. 允许自定义替换文本格式
> 显示视频投稿时间允许自定义替换文本格式

- registry/lib/components/style/dark-mode/dark-slice-17.scss
fix https://github.com/the1812/Bilibili-Evolved/issues/4128
> Preview fixes

- registry/lib/components/style/custom-navbar/built-in-items.ts
- registry/lib/components/style/custom-navbar/index.ts
- registry/lib/components/style/custom-navbar/simple-links/simple-links.ts
参考当前官方的顶栏，独立创作中心按钮。
部分用户（比如我）不想要投稿，但想要创作中心按钮。
> feat: 为自定义顶栏添加单独的`创作中心`

- registry/lib/components/utils/url-params-clean/index.ts
> feat: add url-params-cleaner for bilibili-mall

- registry/lib/components/live/badge-helper/BadgeHelper.vue
- 调整最大列数为15
- https://github.com/the1812/Bilibili-Evolved/issues/4181
> fix: 修正直播间粉丝勋章定位溢出视口问题

- registry/lib/components/utils/ip-show/index.ts
> feat: 添加评论区IP属地显示

- CONTRIBUTING.md
1. 有报错的主要原因应该还是使用了 Volar。代码的问题是一直存在的，跟升级 Vue 2.7 无关。我感觉的话
2. 有关类型的说明放在全局变量的标题下感觉不是很合适，就改了改位置
> 优化了一下 CONTRIBUTING.md 的描述

- registry/lib/components/utils/auto-like/like.vue
> 修复获取用户名称后未去除空白字符导致黑名单无法匹配的问题

- registry/lib/components/utils/auto-like/index.ts
> 修复视频自动点赞失效的问题

- registry/lib/components/style/home-redesign/fresh/init-dropdown-options/area-primary-title-color.ts
- registry/lib/components/style/home-redesign/fresh/layouts/areas/Areas.vue
- registry/lib/components/style/home-redesign/fresh/types.ts
> [组件-清爽首页] feat: 为栏目主标题字体颜色添加浅色样式

- registry/lib/components/style/simplify/live/live.scss
> 直播间简化适配新版pk条

- registry/lib/components/utils/view-cover/Plugin.vue
- registry/lib/components/utils/view-cover/ViewCover.vue
- registry/lib/components/utils/view-cover/index.ts
- registry/lib/components/utils/view-cover/utils.ts
- registry/lib/components/video/download/inputs/video/SingleVideoInfo.vue
- add a plugin in utils/view-cover components for 'downloadVideo' able to download cover.
- reconstruct codes for getting video cover URL.
> [组件-下载视频][组件-查看封面] Add  'download cover' option in 'downloadVideo' component

- registry/lib/components/utils/black-list/index.ts
> Fix(black-list): adapt new home page (fix #4510)

- registry/lib/components/style/dark-mode/dark-slice-18.scss
fix: https://github.com/the1812/Bilibili-Evolved/issues/4599
> Fix:  适配夜间模式下视频播放页的充电卡片

- src/components/video/player-agent/base.ts
> Fix toggleLight

- registry/lib/plugins/video/download/idm-output/index.ts
相关讨论： https://github.com/the1812/Bilibili-Evolved/discussions/2871
简单来说，保留文件名需要第三方软件支持，但文档没写。
> [插件 - 下载视频 - IDM 输出支持] 增加保留文件名相关内容的描述

- registry/lib/components/feeds/legacy-image-viewer/index.ts
现样式：
修改后：
> [评论参考](https://t.bilibili.com/909502424937398360)
> [组件-动态图片平铺展示] fix: 平铺转发的动态

- registry/lib/components/feeds/copy-link/index.ts
- src/components/feeds/api/manager/index.ts
[部分话题页面有视频](https://www.bilibili.com/v/topic/detail/?topic_id=1044382)，可能需测试能否正常工作
> fix: 新版Topic页面支持复制动态链接

- registry/lib/components/utils/black-list/BlackListSettings.vue
> Fix(black-list): Increase the width of the popup box and add a scroll (fix the1812#4749)

- registry/lib/components/style/dark-mode/dark-slice-12.scss
- registry/lib/components/style/dark-mode/dark-slice-18.scss
- registry/lib/components/style/dark-mode/old/dark-slice-1.css
> 修复夜间模式的两个问题

- registry/lib/plugins/video/download/wasm-output/handler.ts
- registry/lib/plugins/video/download/wasm-output/utils.ts
<details>
<summary>预览动图</summary>
</details>
> [插件 - 下载视频 - WASM 混流输出] 并行下载库和音视频流

- registry/lib/components/utils/black-list/Settings.vue
> fix(black-list): remove login check (fix #4917)

- registry/lib/components/style/hide/trending-search/hide-trending-search.scss
- registry/lib/components/style/hide/trending-search/index.ts
> [功能 - 组件 - 隐藏热搜] 添加直播间搜索框的热搜隐藏功能

- registry/lib/components/utils/active-video-links/index.ts
> fix(active-video-links): nicovideo url fix (#5214)

- registry/lib/components/utils/auto-like/index.ts
Closes https://github.com/the1812/Bilibili-Evolved/issues/5221.
> fix: 自动点赞忽略黑名单的问题

- registry/lib/components/video/player/show-upload-time/defaultVideo.ts
- registry/lib/components/video/player/show-upload-time/index.ts
- registry/lib/components/video/player/show-upload-time/mediaListVideo.ts
- registry/lib/components/video/player/show-upload-time/show-upload-time.scss
- registry/lib/components/video/player/show-upload-time/video.ts
> 显示视频投稿时间适配合集类页面

- registry/lib/components/utils/download-emoticons/Widget.vue
- registry/lib/components/utils/download-emoticons/index.ts
> Preview-fixes
