the1812/Bilibili-Evolved

- .vscode/settings.json
- @types/global/index.d.ts
- src/client/settings.js
- src/style/custom-navbar/favorites-list/custom-navbar-favorites-list.ts
以前一直想吐槽的一点，这个收藏列表所选项在跨页面时是不记忆的，如果在收藏列表里打开了某个收藏夹里的视频，又想要在那个视频页面打开同一收藏夹下的其它视频就又得翻一次收藏夹列表，十分不便
这个 pr 改进了这一点，把相关项存储在设置中，这样哪怕关闭浏览器在打开也会直接显示上次所选的收藏夹
> 记忆自定义标题栏收藏列表所选项

- src/client/resource-manifest.js
- src/client/settings.js
- src/global.d.ts
- src/utils/gui-settings/gui-settings.html
- src/utils/gui-settings/icons.css
- src/utils/gui-settings/tooltip/settings-tooltip.zh-CN.ts
- src/video/default-video-speed.ts
- src/video/keymap.ts
来自 #1315
- 修复：通过扩展快捷键修改倍数后，界面元素（倍数菜单）状态与实际情况不一致
- 变更：`useDefaultVideoSpeed` 设置项现在指示是否记忆上次所选的倍数
- 新增：`rememberVideoSpeed` 设置项可指示是否记忆视频级别的倍数
- 依赖 `useDefaultVideoSpeed`，当 `useDefaultVideoSpeed` 设置为 true 时，此设置项才有效 
- 新增：`rememberVideoSpeedList` 设置项用于存储细化到视频级别的倍数记忆值
- 变更： `defaultVideoSpeed` 将指示缺省情况下的默认速度值
- 当启用 `useDefaultVideoSpeed` 并禁用 `rememberVideoSpeed` 时，可通过原生倍数菜单（或快捷键扩展）设置不相同的倍数来修改此值
- 当启用 `useDefaultVideoSpeed` 并启用 `rememberVideoSpeed` 时，如果当前视频没有相应的记忆值，则使用此值作为默认值
- 新增：`extendVideoSpeed` 设置项可指示是否扩展原生倍数（也会影响快捷键扩展的播放速度上限）
> 「默认播放速度」功能改进

- src/style/dark/dark-slice-bnj2021.scss
> [活动页地址](https://www.bilibili.com/festival/2021bnj)
主要修复了一下明晃晃的评论区，以及一些比较明显的样式冲突：
恢复了弹幕列表头部的背景色：
> 夜间模式适配 2021 拜年纪活动页

- src/video/video-speed/video-speed-controller.ts
参考 https://github.com/the1812/Bilibili-Evolved/pull/1570#issuecomment-780542638
这肯定是发生了某种异变（看来还是得在初始化完成之后标记一下
> 修复互动视频在切换剧情分支时，倍数菜单重复初始化的问题

- .editorconfig
- .vscode/extensions.json
- src/style/custom-navbar/custom-navbar.scss
- src/style/custom-navbar/custom-navbar.ts
- src/style/custom-navbar/simple/custom-navbar-rank.ts
- src/style/dark/dark-color-scheme.ts
- src/style/dark/dark-styles.ts
在某一次编译中，编译器抽风了，没做gif。（能写个编译清理之类的task吗
> 附言：
> 前阵子逛知乎，偶然发现我们居然回复过同一个问题。。。就是vscode图标那个，大千世界...唯有缘妙不可言
> Feat#1291 && Fix#1768

- src/utils/gui-settings/tooltip/settings-tooltip.zh-CN.ts
https://github.com/the1812/Bilibili-Evolved/issues/1273
> 更新 夜间模式跟随系统 的说明

- src/global.d.ts
- src/style/home-hidden/home-hidden.scss
- src/style/home-hidden/home-hidden.ts
- src/video/download-video/batch-download.ts
- src/video/scroll-out-player.ts
之前一直没开画中画...发现画中画会导致自动暂停出现一些bug
顺便添加了一些`首页过滤`
> 修复了一些bug, 增加了log信息

- registry/lib/components/video/player/intersection-actions/index.ts
- src/components/video/player-light.ts
1. 给`light`加了个适配器，但是看了下`playerAgent`那边的代码，感觉可以直接把关灯的适配器写到`playerAgent`里，看看你的意见。
2. 修复`播放器位置动作`，改用`playAgent`实现。
另外，我看`autoplay`已经有三个地方用到了，是不是也可以把获取`localStorage`的`bilibili_player_settings`的方法也写到`playerAgent`的实例里。
> New light Adaptor, Fix intersection.

- registry/lib/components/video/player/auto-light/index.ts
- registry/lib/components/video/player/default-mode/index.ts
- registry/lib/components/video/player/intersection-actions/index.ts
- src/components/video/player-agent.ts
- src/components/video/player-light.ts
`player-light` 我把判断是否初始化去掉了，现在每次`setlight`都会去加载一下设置面板。主要是为了应对多P的情况，多P切视频后要去触发一下面板才能关灯。
而且我发现一个问题，`playerAgent`貌似是一个自执行函数，这个函数返回`agent`实例，是特意设计的吗（比如强制使用`playerAgent.xxx`的形式调用实例方法，解构得话会导致`this`丢失）？
那么，如果在一个函数或者是一个功能里多次`playerAgent.xxx`是不是意味着会出现多个`agent`实例。
> PlayerAgent support LightOff action.

- src/client/init.ts
- src/components/settings-panel/index.ts
- src/components/settings-panel/sub-pages/online-registry/OnlineRegistry.vue
...没想到解决办法竟然如此简单, 在 #2349 中提到的 `core-api` 中 ,有些使用了 `requestIdleCallback` 这个 api, 而兼容性补丁则比加载 `core-api` 的过程要晚, 导致了问题.
另外, 我给设置添加了一个来源分支选项, 这对用户影响不大, 但应该可以方便开发者( 有时候自己的仓库里的分支名和上游仓库里的分支名可能不同
> 修复 Safari 无法加载问题

- registry/lib/plugins/video/download/mpv-output-playlist/MpvConfig.vue
- registry/lib/plugins/video/download/mpv-output-playlist/index.ts
- registry/lib/plugins/video/download/mpv-output-playlist/mpv-playlist.ts
- 该插件属于下载视频组件
- 使用该插件，需要安装MPV，能用mpv命令播放video url
- 使用该插件，需要安装[playwithmpv](https://github.com/videoanywhere/playwithmpv)
- 使用该插件的方法：选中对应的输出方式，点击开始按钮，使用本地的MPV播放器打开多P播放列表
> 添加feat - 下载视频：MPV播放支持（列表）插件

- src/ui/VSlider.vue
- 当 min 不为 0 时，点击 slider bar 无法跳到正确的值
- 新增了 start, end 两个事件，监视用户拖动的开始与结束
- 新增 center, fix-num, display-fun 三个 prop
- 修改了值的对齐逻辑
- 修改了 min, max 的含义，同时修改了真实最大与最小值的获取逻辑
- 更改用户操作组件的逻辑：即使父组件不修改 value，组件的 thumb 仍然可以被用户改变位置（通过拖动等）；
此行为与浏览器原生表单类似。
> 重构 VSlider，修复 bug，添加新的功能与行为

- registry/lib/components/video/player/common/speed/context.ts
原因是获取可用倍速数组时，采用了 `innerHTML` 拿到节点文本，但有时生成的 `scoped id`  包含了 `?x` 这种形式的字符串（如上图），导致 `parseSpeedText` 误识别，扩展倍速就会拿到有问题的可用倍速数组，生成不正确的推荐值.
解决方案是换成 `textContext` 获取节点文本.
ps. 这个 BUG 是随机触发的，虽然我今天晚上才发现的，但并不难触发（
> 修复某些情况下扩展倍速可能会出现不正确的推荐值

- src/components/component.ts
- src/core/external-input/index.ts
- src/core/external-input/load-feature-code-all-settled.ts
- src/core/external-input/load-feature-code-all.ts
- src/core/external-input/load-feature-code.ts
- src/core/external-input/load-features-from-codes.ts
- src/plugins/plugin.ts
目前加载组件代码使用的方法是 batchParseCode。该方法的特点是：只要有一个组件抛出异常，就会直接返回 null；而且其错误处理也比较简陋。
这个提交改用了新的 API。新 API 在 feature 抛出异常时，只会输出错误日志，并继续其他组件的加载。
> 改进代码字符串的加载方式2

- registry/lib/components/style/custom-navbar/CustomNavbar.vue
bug 见视频：
<video src="https://user-images.githubusercontent.com/46739861/170842105-dd3d4c46-862e-4360-ae4c-afc6153662a7.mp4" controls></video>
如下图所示，右侧虚线所在的元素采用了绝对定位，且有 `left: 0`，当其宽度为 0 时，border 会出现在顶栏右侧，使得顶栏宽度溢出页面，于是就出现了横向滚动条。
> 修复自定义顶栏右侧 padding 的显示问题

- registry/lib/components/video/player/extend-speed/component.ts
> fix(extend-speed): 修复启用扩展倍速后，倍速列表不显示的问题

- registry/lib/components/feeds/filter/FeedsFilterCard.vue
- registry/lib/components/feeds/unfold/index.ts
- registry/lib/components/video/download/DownloadVideo.vue
- src/components/feeds/BangumiCard.vue
> 新增下载视频时选择是否使用备用下载地址的功能

- registry/lib/components/feeds/filter/FeedsFilterCard.vue
- registry/lib/components/feeds/unfold/index.ts
- registry/lib/components/video/bvid-convert/BvidConvert.vue
- src/components/feeds/BangumiCard.vue
#3794 
修复后，普通视频的「复制链接」会根据AV、BV给出不同链接，并忽略无用的query。如AV号处复制得`https://www.bilibili.com/video/av247571422`。
「带上标题」原本会「将标题写两遍，以 - 分隔」，修复后只会显示一遍。这个的根源在于**`getFriendlyTitle`默认返回的标题就是如此**。我觉得这个默认行为很奇怪，但尝试进一步调试时发现修改本体代码后 网页虽然会自动刷新但根本就没有应用修改后的代码，翻`CONTRIBUTING.md`也没找到该怎么做，就作罢了。目前只在`bvidConvert`这个组件里修改了调用参数，但我感觉这里可能需要进一步除根。
> fix(bvidConvert): copied link

- src/components/bisector/DialogContent.vue
- src/components/bisector/DialogTitle.vue
- src/components/bisector/ResultToastContent.vue
- src/components/bisector/api.ts
- src/components/bisector/bisect.ts
- src/components/bisector/index.ts
- src/components/bisector/options.ts
- src/components/built-in-components.ts
- src/components/types.ts
- src/components/user-component.ts
- src/core/dialog/index.ts
- src/core/utils/index.ts
和 vscode 的「扩展二等分」功能类似，可帮助开发人员定位是哪个组件导致的问题。
idea 来自：#3829
目前支持两种方式唤起二等分操作：
- 通过 launchBar（搜索栏），输入「二等分」
- 通过 `componentApis` API，在控制台中调用 `bilibiliEvolved.componentApis.bisectComponent` 方法
API 方式可指定需要固定启用或禁用状态的组件，以便进一步缩小范围。例如，下面的调用方式表示在始终启用「记忆倍速」和「扩展倍速」组件的情况下，对其他组件进行二等分：
```javascript
const bisector = await bilibiliEvolved.componentApis.bisectComponent({keepEnabledComponents: ["extendVideoSpeed", "rememberVideoSpeed"]})
bisector.start()
```
[视频2.webm](https://user-images.githubusercontent.com/34429322/216808529-a9d44f8a-dc19-49c3-824f-3217b77d6ae8.webm)
[视频.webm](https://user-images.githubusercontent.com/34429322/216775158-517e2763-0578-4e5c-9d2c-b799245db942.webm)
> feat: 组件二等分

- src/components/settings-panel/sub-pages/manage-panel/UserItem.vue
`removeConfirmTemplate` 和 `removeIcon` 仅在 `this.config.isUserItem` 时才存在。所以需要限制 Toast 的显示条件，避免传入 `null`。
> Fix UserItem.vue

- registry/lib/components/style/hide/user-card/index.ts
- registry/lib/components/style/hide/user-card/user-card.scss
> [新增组件]隐藏用户信息卡片

- src/components/utils/comment-apis.ts
在 `CommentItem` 内新增了 `pictures` 值，从 `vueData` 解析评论区笔记图片链接为数组
简单测试了可以正常获取 无/单张/多张 评论图片
> 向 comment-apis 添加评论图片支持

- registry/lib/components/feeds/extend-live/index.ts
参照：#4034、#3917
直播信息扩充组件，在新版动态下，十个之后的直播间无法点击进入。而旧版动态没问题，所以做了下兼容。
> fix(extend-live): 修复新版动态无法打开“正在直播”十个以后的链接

- registry/lib/components/video/player/disable-scroll-volume/index.ts
- src/components/video/player-adaptor/bpx.ts
- src/ui/_common.scss
[fix: 修正播放器模式切换时 body类名响应问题](https://github.com/the1812/Bilibili-Evolved/commit/5d132bbe3eb58fb799b16cc549327149be0c87b7) 
- 调整了应用到`body`的类名
- `player-mode-webfullscreen` => `player-mode-full`
- `player-mode-widescreen` => `player-mode-wide`
[fix: 适应 bpx.ts 中类名变化](https://github.com/the1812/Bilibili-Evolved/commit/ac6e0e40f7082633a96180382eada2d34dd20fc3) 
- 全局搜索只找到了这一处，不知道还有没有其他地方
> fix: 修正播放器模式切换时 body类名响应问题

- registry/webpack/build.ts
- 之前展示的是完整路径 当路径过长时会导致提示信息过长 选取体验很差
- 做统一截取处理 只展示能够区分当前组件的部分
- 可以优化部分场景下的开发体验：比如下例中将终端放在一侧的场景
- 组件、插件、doc做了统一处理
- 这里使用`replace`局部替换的代码中，使用的`/`分隔符是否适用于Windows存疑
处理前：
> <img width="25%" alt="Snipaste_2023-05-10_17-12-49" src="https://github.com/the1812/Bilibili-Evolved/assets/64892985/348ddb12-f424-4b65-993b-e01bf641c62d">
处理后：
> <img width="25%" alt="Snipaste_2023-05-10_17-12-22" src="https://github.com/the1812/Bilibili-Evolved/assets/64892985/c25b1d0f-8313-4ef0-9d2a-56192445f02b">
[build: 缩短构建组件时CLI提示长度](https://github.com/the1812/Bilibili-Evolved/commit/bd3b452631fe0e39f8d932b0fff4da63bbdfc047) 
- 之前展示的是完整路径 当路径过长时会导致提示信息过长 选取体验很差
- 做统一截取处理 只展示能够区分当前组件的部分
> build: 截取构建时CLI提示信息 | intercept the CLI prompt information during the build

- registry/lib/components/utils/url-params-clean/index.ts
> feat: + `live_from`

- registry/lib/components/style/custom-navbar/favorites/NavbarFavorites.vue
- registry/lib/components/style/custom-navbar/history/NavbarHistory.vue
- registry/lib/components/style/custom-navbar/subscriptions/SubscriptionsList.vue
- registry/lib/components/style/custom-navbar/watchlater/NavbarWatchlater.vue
原因：自定义顶栏的图片使用了 CSS 类 cover-container；该类被 B 站使用，进而影响到自定义顶栏
修复方式：更改使用的 CSS 类名
> Fix image style of customNavbar(fix #4312)

- registry/lib/components/utils/comments/copy-link/index.ts
- registry/lib/components/utils/ip-show/index.ts
- registry/lib/deprecated/comments-translate/index.ts
- src/components/utils/comment-apis.ts
刚刚发现IP属地展示在处理新版评论区的楼中楼回复时会出错（应查找`.sub-reply-info>.sub-reply-time`而不是`.reply-info>.reply-time`），已修复该问题
另外我还发现`onRepliesUpdate`只能处理旧版评论区的展开和翻页，对于新版评论区无效（依赖此功能的复制评论链接也受此影响）
可以将`/src/components/utils/comment-apis.ts`第113行开始的
```
childList(replyBox, () => {
item.replies = parseReplies()
})
```
替换为
```
childList(replyBox, () => {
item.replies = parseReplies()
item.onRepliesUpdate?.(item.replies)
})
```
来对此进行修复
但这样带来了一个新问题，目前项目里使用了`onRepliesUpdate`这个功能的就只有我这个IP属地显示（`ipShow`）以及原先的复制评论链接（`copyCommentsLink`），也就是说原先使用此功能的只有复制评论链接这一个组件。现在我的IP属地显示同样需要使用这个功能，但`onRepliesUpdate`只能同时绑定一个回调函数，经测试开启复制评论链接后，IP属地显示将会无法处理新版评论区的回复更新
> 修复IP属地显示在处理楼中楼回复时的问题

- .eslintrc.js
- CONTRIBUTING.md
- package.json
- pnpm-lock.yaml
- registry/webpack/config.ts
- src/client/init-vue.ts
- tsconfig.json
- webpack/webpack.config.ts
- webpack/webpack.dev.ts
- webpack/webpack.prod.ts
不涉及 core 与任何 feature 代码的更改。仅升级 vue 及相关工具。
可在正式升级 vue 3 之前，提供组合式 API 支持，而不破坏已有代码（限制：[与 Vue 3 的行为差异](https://v2.cn.vuejs.org/v2/guide/migration-vue-2-7.html#%E4%B8%8E-Vue-3-%E7%9A%84%E8%A1%8C%E4%B8%BA%E5%B7%AE%E5%BC%82)）。
推荐插件改为 Volar。
> 升级到 Vue 2.7 | 提供组合式 API，且无需修改现有代码

- registry/lib/components/utils/subscribe-time-show/index.ts
- registry/lib/components/utils/subscribe-time-show/subscribe-time.scss
在关注/粉丝列表中显示用户/粉丝关注的具体时间
效果图
注：分组的关注列表里不显示关注时间并不是bug，而是分组关注里b站的api确实没有返回关注时间（
还有就是我感觉现在的关注时间显示有点丑，有没有人能想出更好看一点的样式
> feat: 添加粉丝/关注列表关注时间显示

- registry/lib/components/style/custom-navbar/_nav-link.scss
- registry/lib/components/style/custom-navbar/entry.ts
- registry/lib/components/style/custom-navbar/index.ts
- registry/lib/components/style/custom-navbar/link-popup-content-align-style.ts
Complete #4255
为导航栏使用 `nav-link` style 的弹窗增加更多的对齐样式
另外想问一下，这个设置描述应该写什么最为恰当，现在的总感觉有些词不达意 🤔
设置入口：
左侧对齐：
居中对齐：
右侧对齐：
_额外提一嘴，这次细细倒腾了一下，感觉之前开发版本 (Local) 没法用的问题，可能是由于长时间连接不上 raw.githubusercontent.com 导致无法加载 lodash.min.js 引起的，或许未来可以在 [CONTRIBUTING.md](https://github.com/the1812/Bilibili-Evolved/blob/master/CONTRIBUTING.md) 加一条关于它的提醒，以方便排查问题_
> [组件-自定义顶栏] feat: 为导航栏使用 `nav-link` style 的弹窗增加更多的对齐样式

- registry/lib/components/style/custom-font-family/disable-quotation-mark-text-indent.scss
- registry/lib/components/style/custom-font-family/extra-options/entry.vue
- registry/lib/components/style/custom-font-family/extra-options/extra-options-panel.scss
- registry/lib/components/style/custom-font-family/extra-options/panel.vue
- registry/lib/components/style/custom-font-family/extra-options/vm.ts
- registry/lib/components/style/custom-font-family/font-family-default-value.ts
- registry/lib/components/style/custom-font-family/index.ts
- registry/lib/components/style/custom-font-family/set-font-family.scss
新增组件 `自定义字体`。
启用后，可以使用组件提供的字体设置覆盖原版的主站字体，且主站字体能够随时自定义。
> [组件-自定义字体] feat: 新增组件 `自定义字体`

- registry/lib/components/live/original/Widget.vue
- registry/lib/components/live/original/get-original-liveroom-url.ts
- registry/lib/components/live/original/index.ts
complete #4399
功能默认关闭。在组件设置中开启后，当直播间页面不是原版（blanc）时，会自动跳转至原版直播间。
> [组件-返回原版直播间] feat: 增加默认返回原版直播间功能

- registry/lib/components/video/download/apis/dash.ts
- registry/lib/components/video/download/index.ts
允许配置 DASH 下载的文件拓展名。
主要的目的是如果用户希望下载后使用 ffmpeg 合并下载后的视频和音频并生成 MP4 封装文件时，可以将视频下载为 `.m4v` 文件，从而避免文件命名的拓展名冲突。
现在下载后的文件：
```
DemoFoobar_哔哩哔哩bilibili_APEX英雄.m4a
DemoFoobar_哔哩哔哩bilibili_APEX英雄.mp4
```
用户需要使用命令
```
ffmpeg -i DemoFoobar_哔哩哔哩bilibili_APEX英雄.m4a \
-i DemoFoobar_哔哩哔哩bilibili_APEX英雄.mp4 \
-codec copy \
DemoFoobar_哔哩哔哩bilibili_APEX英雄.full.mp4
rm -rf DemoFoobar_哔哩哔哩bilibili_APEX英雄.m4a
rm -rf DemoFoobar_哔哩哔哩bilibili_APEX英雄.mp4
mv DemoFoobar_哔哩哔哩bilibili_APEX英雄.full.mp4 DemoFoobar_哔哩哔哩bilibili_APEX英雄.mp4
```
如果允许用户自定义拓展名，则用户可以设置视频文件下载拓展名为 `.m4v`，将文件下载为
```
DemoFoobar_哔哩哔哩bilibili_APEX英雄.m4a
DemoFoobar_哔哩哔哩bilibili_APEX英雄.m4v
```
这样合并文件后只需要删除 `.m4a` 和 `.m4v` 即可，生成的 `.mp4` 文件的文件名则可以和原来的 `.m4v`/`.m4a` 文件保持一致。
> feat: 允许配置视频下载文件拓展名

- registry/lib/components/feeds/disable-details/index.ts
图文动态找不到 `.bili-dyn-content__orig__desc`
新增 `.dyn-card-opus__summary` 即可修复
目前图文动态内容部分的完整选择器
```javascript
document.querySelector(
`.bili-dyn-item__main > .bili-dyn-item__body >
.bili-dyn-content > .bili-dyn-content__orig.reference > .bili-dyn-content__orig__major >
.dyn-card-opus > .dyn-card-opus__summary`
)
```
> fix: 修复被转发图文动态的 `详情 >` 功能失效

- registry/lib/components/style/home-redesign/minimal/tabs/Feeds.vue
- src/ui/ScrollTrigger.vue
fix #4302
如题，当 `ScrollTrigger` 初次触发加载且父级组件完成加载后，如果因为高分屏、低缩放比例等原因，使 `ScrollTrigger` 仍在视口内部的话，将会导致 `IntersectionObserver` 无法继续触发，接着导致组件无法自动触发加载，最后导致受影响用户遇到父级组件不会自动继续加载的问题。
无法继续触发 `IntersectionObserver` 的原因是，此时页面滚动不了，`ScrollTrigger` 无法离开和进入视口。
这个 PR 通过为 `ScrollTrigger` 增加可视判断逻辑来修复上述问题，同时可以解决 #4302 报告的情况。
由于问题描述有点区别，可能没有解决[这条回复](https://github.com/the1812/Bilibili-Evolved/issues/4302#issuecomment-1712458025)和 #4428 遇到的问题，需要后续反馈才能确认具体情况。
另外，为了避免可视判断逻辑造成的重复加载情况，这个修复方法还需要修改用到 `ScrollTrigger` 并且需要它的可视判断逻辑的组件代码，使其能够向 `ScrollTrigger` 传递加载状态。
考虑到一次性全改了可能会出现奇奇怪怪的问题，所以这个 PR 只调整了有问题报告的极简首页组件，可以先看看效果。
> [组件-极简首页] fix: 修复 `ScrollTrigger` 在特定情况下无法触发加载的问题

- registry/lib/plugins/video/download/wasm-output/ffmpeg.ts
- registry/lib/plugins/video/download/wasm-output/handler.ts
- registry/lib/plugins/video/download/wasm-output/index.ts
- registry/lib/plugins/video/download/wasm-output/utils.ts
参见讨论 https://github.com/the1812/Bilibili-Evolved/discussions/4518
问题：
- GitHub 上没有找到相关的文件，只能从 jsDelivr 上加载，无法使用 `altCdn`
> [新增插件] 使用 WASM 在浏览器中下载并混流音视频

- registry/lib/plugins/video/download/wasm-output/ffmpeg.ts
- registry/lib/plugins/video/download/wasm-output/handler.ts
- registry/lib/plugins/video/download/wasm-output/utils.ts
- webpack/cdn/github.ts
- webpack/cdn/jsdelivr.ts
- webpack/cdn/types.ts
> 修复 #4521 中审查的问题

- registry/lib/components/utils/ip-show/index.ts
修复[#4572](https://github.com/the1812/Bilibili-Evolved/issues/4572)
小黑屋中使用的旧版评论区脚本和其他地方的不一样，故进行了特判
> fix: 修复IP属地显示在小黑屋中失效的问题(fix #4572)

- README.md
> feat(README.md):微调文档格式

- registry/lib/components/feeds/extend-live/LiveList.vue
- New API will retrieve live rooms including 'quietly follow' (悄悄关注) users. The previous API does not.
- Add post-process: to maintain the order in the web dynamic dashboard, reorder the list after retrieving all live rooms.
(The list needs to be reordered, so I await all items. That is different from before (updating lists responsively). Not sure there is any better approach)
- CSS scope formatted by Linter.
> [组件-直播信息扩充]feat: use new live feeds api and add reorder post-process

- registry/lib/components/utils/url-params-clean/index.ts
https://github.com/the1812/Bilibili-Evolved/issues/4656
> [组件-网址参数清理] 修复重新打开关闭的搜索页时跳转至 https://search.bilibili.com/undefined

- registry/lib/components/feeds/disable-details/index.ts
例如 https://t.bilibili.com/904142297159958549
> [组件-禁止跳转动态详情] fix: 修复带图转发动态的 `查看图片` 失效

- registry/lib/plugins/video/download/wasm-output/database.ts
- registry/lib/plugins/video/download/wasm-output/handler.ts
- registry/lib/plugins/video/download/wasm-output/utils.ts
参见议题 #4648：
由于浏览器缓存机制，WASM 文件缓存失效很快。
（个人猜测可能是因为文件过大，具体原因没来得及调查验证。）
使用 IndexedDB 持久缓存相关文件 ~~，数据库版本使用 Bilibili-Evolved 的版本号~~。
此次本插件更新后，正常情况下，以下情景会下载相关文件并创建/更新缓存：
- 第一次使用本插件
- 清除浏览器缓存后再次使用本插件
- ~~Bilibili-Evolved 更新后再次使用本插件~~
---
抱歉刚刚 PR 错分支了，我记得能改的啊，但是点了 Edit 之后，目标分支没有下拉选择了（[图](https://p.sda1.dev/16/c0742b0aad82bcd3fad0c6392b8de1e3/20240304230018.png)）？
关于我多次提到的 “基于 WebCodecs 的插件”（#4648、#4615），因为我近期确实没有太多空闲时间来仔细研究 WebCodecs，所以可能短期内写不出来了，于是就凑了点时间先把 WASM 插件的缓存做了。
> [插件 - 下载视频 - WASM 混流输出] 持久缓存相关文件

- registry/lib/components/style/dark-mode/dark-slice-13.scss
- registry/lib/components/style/dark-mode/dark-slice-18.scss
- registry/lib/components/style/dark-mode/dark-slice-9.scss
此 PR 为视频播放页的两个 popover 适配了深色模式：
- AI 视频总结
<details>
<summary>截图</summary>
</details>
- 视频笔记
<details>
<summary>截图</summary>
<p float="left">
</p>
</details>
> fix: 为视频播放页的两个 popover 适配深色模式

- registry/lib/components/feeds/copy-link/index.ts
- src/components/feeds/api/manager/index.ts
若为直发图文动态，opus格式链接有收藏按钮，t没有。
若为转发类动态，会自动跳转到t。
故改用opus
> feat: 复制动态链接改用`opus`

- registry/lib/components/video/danmaku/converter/danmaku-segment.ts
有用户 [向 pakku 反映](https://github.com/xmcp/pakku.js/issues/274) 开启 pakku 之后用 Bilibili-Evolved 下载的仍然是处理之前的原始弹幕，导致他还要手工处理一下，比较麻烦。
这是因为 pakku 曾经 hook 了 XMLHttpRequest，而且处理得有问题，导致 [Bilibili-Evolved 改用 fetch 来下载（未经 pakku 修改的）弹幕](https://github.com/xmcp/pakku.js/issues/153)。
刚更新的 pakku v2024.4.3 版本解决了兼容性问题，同时也 hook 了 `fetch` 函数，这样两个插件就可以共存了。可以 [安装新版 pakku 试一下效果](https://s.xmcp.ltd/pakkujs/)。
我本地测试了一下，把 Bilibili-Evolved 下载弹幕代码的  `fetch()`  改成 `unsafeWindow.fetch()` 即可下载 pakku 处理之后的弹幕（如未安装新版 pakku 时则会正常调用原始的 `fetch`）。
> fix: 同时安装了pakku时下载处理后的弹幕

- registry/lib/components/video/player/legacy-auto-play/index.ts
目前，传统连播模式组件仅支持带有自动连播按钮的相关网页。在特殊情况下会导致某些不存在自动连播按钮的网页的连播设置被篡改，例如，视频列表的播放网页。此 PR 修复了传统连播模式组件无法处理视频列表的播放页面的情况。主要用于增加传统连播模式组件的兼容性。
注意：如果 B 站的播放页面出现变动，则组件也需要做出相应的变动。如果出现新的播放形式的页面，也可能需要对组件进行更新。
#4699
> 为传统连播模式组件添加识别和处理视频列表的播放网页的相关功能。

- registry/lib/components/video/player/show-upload-time/index.ts
- src/components/video/video-info.ts
1. 修复显示时间错误问题（对于2017年前的视频大概率时间显示为2017年）
2. 修复不刷新页面切换视频时部分视频投稿时间不显示问题
> 显示视频投稿时间——修复时间显示错误及不显示时间问题

- registry/lib/components/live/remove-mask-panel/index.ts
删除观看直播时某些分区的马赛克遮罩。例如守望先锋分区会自动添加两个马赛克遮罩，pr 提供了去除此类遮罩的能力
删除遮罩前：
删除遮罩后：
> [feature] 删除直播马赛克遮罩

- registry/lib/components/utils/view-cover/index.ts
- registry/lib/components/video/download/DownloadVideo.vue
- registry/lib/components/video/download/types.ts
- registry/lib/plugins/video/download/aria2-output/RpcConfig.vue
- registry/lib/plugins/video/download/aria2-output/aria2-rpc.ts
1. 优化视频下载组件的结构，现在在调用 `downloadExtraAssets` 时候再获取 assets 的 blob 并下载
2. 扩展视频下载组件的接口，插件可以处理 assets 的下载逻辑
3. 扩展视频封面组件和 aria2 插件以支持 aria2 下载封面
> [组件-下载视频][插件-下载视频 - aria2 输出支持][组件-查看封面] 为aria2提供可下载封面的功能

- registry/lib/components/style/special-danmaku/special-danmaku.scss
- registry/lib/components/video/player/remove-popup/remove-popup.scss
fix #4831 , fix #4823 
目前部分设备**删除视频弹窗失效、禁用特殊弹幕样式失效**，像灰测，已知 Safari 会出现这一情况，可尝试在 Chrome 复现：
1. 用 Safari 的 UA 访问视频页，head 内会出现与 Chrome 不同哈希值的 core.js （要看运气）
2. 在 Chrome 内使用 https://github.com/fengyc/URLRedirector 对 core.js 链接进行重定向，即可获得带有 `-x-` 特征的弹幕和弹窗
3. 分析可知新版弹窗样式在 widget js 文件内 [样本链接](https://s1.hdslb.com/bfs/static/player/main/widgets/npd.579.b4368336.js)
4. 不知道 B 站什么时候继续改类名（或者放弃铺开测试），但愿多生效一阵
PS.
1. 弹窗屏蔽 scss 代码里视频预告的测试链接失效了，暂未找到替代链接
2. 禁用特殊弹幕样式，大会员弹幕可以在描边类型修改时实时变化，但普通弹幕不会变，原因是官方没做
> Fix: 删除视频弹窗、禁用特殊弹幕样式适配灰测

- registry/lib/components/live/liveroom-username-link/index.ts
网页版直播间右上角的房间观众和大航海界面的用户列表只可查看用户名，不可进行点击。
该组件为用户头像和用户名称处添加点击效果，允许通过点击直接查看用户空间。
> feat: 为直播间用户添加超链接

- registry/lib/components/video/player/show-upload-time/index.ts
- registry/lib/components/video/player/show-upload-time/show-upload-time.scss
> 显示视频投稿时间适配新版推荐列表

- registry/lib/components/feeds/extend-live/LiveList.vue
See: [Discussion #4908](https://github.com/the1812/Bilibili-Evolved/discussions/4908)
> [动态-直播信息扩充] 更新API接口，简化获取逻辑

- registry/lib/components/feeds/del-feeds/check-in-item.ts
修复`registerAndGetData`的`key`错误使用导致同时开启`签到助手`时, 显示两次`签到助手`的按钮
> Fix deleteFeeds

- registry/lib/components/feeds/disable-details/index.ts
例如 https://t.bilibili.com/991837283011264531
> [组件-禁止跳转动态详情] fix: 修复带图转发动态二次转发后，`查看图片` 失效

- registry/lib/plugins/video/download/wasm-output/Config.vue
- registry/lib/plugins/video/download/wasm-output/ffmpeg.ts
- registry/lib/plugins/video/download/wasm-output/handler.ts
- 修复： `写入元数据` 选项不能保存：https://github.com/the1812/Bilibili-Evolved/pull/4840#issuecomment-2439787447
- 新增：混流进度反馈
- 优化：混流结束后删除 Web Worker 中的文件，优化多集下载
> [插件 - 下载视频 - WASM 混流输出] 修复写入元数据选项,  新增混流进度, 优化多集下载

- registry/lib/plugins/video/download/wasm-output/handler.ts
- registry/lib/plugins/video/download/wasm-output/index.ts
> [插件 - 下载视频 - WASM 混流输出] 超过 4GB 时抛出错误

- CONTRIBUTING.md
- dev-tools/dev-server/watcher-common.ts
遇到了和 https://github.com/the1812/Bilibili-Evolved/pull/4076#discussion_r1948041407 一样的问题：文档中没有如何启动 dev-server 的内容，于是补上了；顺便修复了一个变量命名问题
> docs: 优化启动 dev-server 的文档

- registry/lib/components/style/hide/trending-search/hide-trending-search.scss
- registry/lib/components/style/hide/trending-search/index.ts
老版隐藏热搜：
1. 点击搜索框才重置 placeholder 为 “搜索”，默认还是会展示热搜词
2. 没有搜索词的时候，搜索面板的 padding 不为 0 导致会显示一个空白的面板
针对这两点进行了优化，效果 gif：
> [组件 - 隐藏热搜] feat: 优化隐藏热搜的显示效果

- registry/lib/components/style/dark-mode/dark-slice-19.scss
#5163  和[本页面](https://passport.bilibili.com/login)其他未适配的元素
> fix: 夜间模式二维码扫码登录困难 #5163

- registry/lib/components/utils/active-video-links/index.md
- registry/lib/components/utils/active-video-links/index.ts
(Fixed the issue that I previously selected the target merging branch as `main` #5196)
这个组件会将视频简介中的普通网址转换为可点击的链接，并将已失效的 `acg.tv` 跳转链接修复为 `nicovideo.jp` 链接。
例如: `https://acg.tv/sm37507315` → `https://www.nicovideo.jp/watch/sm37507315`
> Re: [新增组件-视频链接增强] feat(components): Active Video Links 

- registry/lib/components/style/dark-mode/dark-slice-15.scss
启用暗黑模式后，当前效果：
原因是里面有三个图标存在不同颜色的 path 被改了颜色，撤销 `fill('e')` 可以发现这一点：
因此这里改成直接对图片反色，并适当调整了色相和亮度：
实际上这个方案对大部分 svg 图片来说几乎都是通用的。
> 修复暗黑模式首页右侧 svg 图标颜色

- registry/lib/components/video/danmaku/airborne/airborne.scss
- registry/lib/components/video/danmaku/airborne/index.ts
增加弹幕空降功能识别中文数字的功能，如图：
顺便修复弹幕空降对特殊弹幕（如高赞弹幕）因dom结构不同不会被正确显示以及触发的问题。
> [组件 - 弹幕空降] 识别中文数字

- registry/lib/components/video/auto-remove-watchlater/index.ts
测试方法：稍后再看切换上一个下一个n次，就会重复监听n次（可以查看video标签的ended事件），导致重复调用接口n次
还有个 跳过充电鸣谢 似乎也有这个问题，但是充电鸣谢好像下线了所以不修了
> [组件-自动移出稍后再看] 优化事件监听逻辑，防止重复监听导致重复调用接口

- registry/lib/components/style/hide/user-card/user-card.scss
讨论 #5324
(评论区的用户信息卡片用上了 Shadow DOM，但是右上角 UP 主的还是以前的
> [组件 - 隐藏用户信息卡片] 修复以适配新版评论区

- registry/lib/components/live/badge-keepalive/utils.ts
使用"返回原版直播间"功能情况下，location变为/blanc/{$room_id}，"点亮粉丝勋章"功能无法自动获取room_id，该修复兼容了这种情况
> 获取room_id兼容blanc原版直播间

- registry/lib/components/video/player/custom-auto-play/AutoplayActionType.ts
- registry/lib/components/video/player/custom-auto-play/handlers/BangumiAutoplayHandler.ts
- registry/lib/components/video/player/custom-auto-play/handlers/BaseAutoplayHandler.ts
- registry/lib/components/video/player/custom-auto-play/handlers/FavoriteAutoplayHandler.ts
- registry/lib/components/video/player/custom-auto-play/handlers/MultipartAutoplayHandler.ts
- registry/lib/components/video/player/custom-auto-play/handlers/PlaylistAutoplayHandler.ts
- registry/lib/components/video/player/custom-auto-play/handlers/RecommendAutoplayHandler.ts
- registry/lib/components/video/player/custom-auto-play/handlers/WatchLaterAutoplayHandler.ts
- registry/lib/components/video/player/custom-auto-play/index.ts
更新内容如下（按commit先后顺序）：
- 将之前各类型页面逻辑处理的类移动到独立文件，仅import、export之类的必要修改，类内部代码无变更（本来想加个装饰器自动实例化，没有引用的话就触发不了，搞半天终于还是和解了，~~GPT还是救不了菜鸡~~）
- 将视频合集（不同BV号）与分P视频（同一BV号）页面拆分为两个选项独立控制
- 修复番剧正片为纯数字列表（以前好像只有图片列表？记不得了）时自动模式失效
> 【组件-定制自动连播行为】修复部分页面不工作
